/**
 * Generated from the repository root VERSION file by scripts/set-version.ps1.
 * Do not edit this file manually.
 */
export const APP_VERSION = '140.0.0.0';
export const APP_VERSION_DISPLAY = '140.0.0';
